version: '3.9'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: dob-ecommerce-app:latest
        container_name: dob-ecommerce-server
        env_file:
            - .env
        depends_on:
            - redis
        ports:
            - 9000:9000
            - 7001:7001
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        environment:
            REDIS_URL: redis://cache

    redis:
        image: redis:7.0.7-alpine
        restart: always
        container_name: cache
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data

volumes:
    redis_data:
    node_modules:
