name: Staging CI/CD
on:
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.STAGING_FILE_ENV }}" > .env
      - name: Run build
        run: npm run build --if-present
      - name: Run migrations
        run: npx medusa migrations run
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            .env
            package.json
            package-lock.json

  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: List contents of current directory
        run: ls -la
      - name: Deploy to staging
        run: |
          # Ensure the deployment directory exists
          mkdir -p ~/dob-server
          
          # Copy new files to the deployment directory
          cp -R dist/* ~/dob-server/ || echo "No dist directory found"
          cp .env ~/dob-server/ || echo "No .env file found"
          cp package.json ~/dob-server/ || echo "No package.json found"
          cp package-lock.json ~/dob-server/ || echo "No package-lock.json found"
          
          # Navigate to the deployment directory
          cd ~/dob-server
          
          # Install production dependencies
          npm ci
          
          # Restart or start the PM2 process
          if pm2 list | grep -q "backend"; then
            echo "Updating existing PM2 process..."
            pm2 reload backend --update-env
          else
            echo "Starting new PM2 process..."
            pm2 start npm --name "backend" -- start
          fi
          pm2 save