name: Production CI/CD
on:
  pull_request:
    branches: ['production']
jobs:
  build:
    runs-on: ["self-hosted", "ubuntu"]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.PROD_FILE_ENV }}" > .env
      - name: Run build
        run: npm run build --if-present
      - name: Run migrations
        run: npx medusa migrations run
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            .env
            package.json
            package-lock.json

  deploy:
    runs-on: ["self-hosted", "ubuntu"]
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: List contents of current directory
        run: ls -la
      - name: Copy files to Production
        run: |
          # Ensure the deployment directory exists
          mkdir -p ~/dob-server

          # Copy new files to the deployment directory
          cp -R dist/* ~/dob-server/ || echo "No dist directory found"
          cp .env ~/dob-server/ || echo "No .env file found"
          cp package.json ~/dob-server/ || echo "No package.json found"
          cp package-lock.json ~/dob-server/ || echo "No package-lock.json found"

          # Navigate to the deployment directory
          cd ~/dob-server
      - name: Install dependencies for Production deployment
        run: |
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "PATH: $PATH"
          echo "NVM_DIR: $NVM_DIR"
          which node || echo "node not found in PATH"
          which npm || echo "npm not found in PATH"
          su dobtech 
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "PATH: $PATH"
          echo "NVM_DIR: $NVM_DIR"
          which node || echo "node not found in PATH"
          which npm || echo "npm not found in PATH"
          npm ci
      - name: Deploy to Production pm2
        run: |
          # Restart or start the PM2 process
          if pm2 list | grep -q "backend"; then
            echo "Updating existing PM2 process..."
            pm2 reload backend --update-env
          else
            echo "Starting new PM2 process..."
            pm2 start npm --name "backend" -- run start:deploy
          fi
          pm2 save
      - name: Verify deployment
        run: |
          echo "Waiting for the application to start..."
          sleep 10  # Adjust this value based on your application's startup time
          if pm2 list | grep -q "backend.*online"; then
            echo "Deployment successful. Application is running."
          else
            echo "Deployment may have failed. Check application logs."
            exit 1
          fi
